language: scala
sudo: false
scala:
   - 2.10.6
   - 2.11.8
jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache

matrix:
  include:
    - scala: 2.12.0-M5
      jdk: oraclejdk8
